#!/usr/bin/env bash
# This script can be run as a command and it is use
# to remove files which is not useful
# It differs from other unused file deleting script
# as it provide you the interactive opportunity to check the
# content of a file before deleting the file

# list of colors that we are using
RED=31
# You have to specify the directory using -d
if [[ $# -eq 0 ]] || [[ ! -e "$1" ]] || [[ $# -gt 1 ]]
then
	echo -e "\e[;31m Usage: clear [command] directory_name \e[0m"
	exit 2
fi

# If you specify file as the argument it is going to ask you
# if you want to check the content of the file.
# if after checking the content of the file you insist of deleting
# then it will delete it
if [[ -f $1 ]]
then
	echo -e "Check content before del ? yes or no"
	read check_content
	if [[ "$check_content" == "yes" ]]
	then
		cat $1
		sleep 2

		echo -e "Do you still want to remove the file yes or no?"
		read remove_file

		if [[ "$remove_file" == "yes" ]]
		then
			rm $1
		fi
	else
		rm $1
		echo "Succesfully removed the file"
	fi
fi

#todo :- Write function for different cases, if the arguments is either file or folder
